# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CrewPass
name: CrewPass
email: adrifelcha@gmail.com
location: Coyoacán, México
company: UNAM
#company_url: my_company_website
#github_url: my_github_url # ex. https://github.com/DONGChuan
#github_username: # ex. DONGChuan
description: Certificación en protocolos de seguridad, sanitización e higiene para la industria audiovisual
#favicon: favicon.png # Image must be in assets/images
#repository: github_username/github_username.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
#url: http://localhost:4000



theme: jekyll-theme-cayman
